{
    'name': 'Recruitment Talent Pool',
    'version': '1.0',
    'summary': 'Beheer talenten en sollicitaties via een centrale pool',
    'description': 'Voegt een Talent Pool toe aan Odoo Recruitment.',
    'author': 'Pascal & Copilot',
    'category': 'Recruitment',
    'depends': ['hr_recruitment', 'portal'],
    'data': [
        'security/talentpool_security.xml',
        'security/ir.model.access.csv',
        'views/res_users_views.xml',
        'views/dashboard_views.xml',
        'views/talent_views.xml',
        'views/portal_talent_views.xml',
        'views/portal_applications.xml',
        'views/portal_education.xml',
        'views/portal_experience.xml',
        'views/portal_skills.xml',
        'views/portal_education_add.xml',
        'views/portal_experience_add.xml',
        'views/portal_skills_add.xml',
        'views/portal_apply_form.xml',            
        'views/portal_menu.xml',            
        'views/hr_applicant_views.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
}
